name: Run Telegram Bot

on:
  push:
    branches:
      - main  # Запускать только при пуше в ветку main

jobs:
  run-bot:
    if: contains(github.event.head_commit.message, 'startbot')  # Запускать только при коммите с сообщением "startbot"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Укажите версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Токен бота из Secrets
        run: |
          python bot.py
